language: minimal
sudo: required

env:
  global:

before_install:
- echo "before_install"

install:
- echo "install"

before_script:
- curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip"
- unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
- mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
- terraform -v
- ssh-keygen -f ~/.ssh/id_rsa -P ""
- echo $TF_VAR_packet_project_id

script:
- echo 'script'
- terraform init 
- terraform validate
- terraform apply -auto-approve
- terraform destroy -auto-approve
